version: '3.8'
volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: lesash13/foodgram_backend:latest
    restart: always
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: lesash13/foodgram_frontend:latest
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend