# Generated by Django 3.2.18 on 2023-04-01 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorites',
                'verbose_name_plural': 'Favorite Recipes',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ingredient Title')),
                ('measurement_unit', models.CharField(max_length=200, verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'General ingredients amount',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Recipe title')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Recipe image')),
                ('text', models.TextField(verbose_name='Recipe description')),
                ('cooking_time', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Cooking time must be at least 1 minute')], verbose_name='Cooking time')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Pub date')),
            ],
            options={
                'verbose_name': 'Recipe',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Amount must be at least 1')], verbose_name='Ingredient amount')),
            ],
            options={
                'verbose_name': 'Ingredient amount',
                'default_related_name': 'ingredients_recipe',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Color HEX code')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='recipes.recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Recipe in basket',
            },
        ),
    ]
